### ISSUE TITLE
Not working anymore in React Native / Expo

### ISSUE THREAD

**Issue by enguerranws** [danang-id/simple-crypto-js#24]
Hi,

Since I updated from 2.2.0 to 2.4, my Expo (React Native) app, stopped working properly, throwing this error on decrypt:

```
The package at "node_modules/crypto-js/core.js" attempted to import the Node standard library module "crypto". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
```

Any idea how to fix that?

**Comment by danang-id** [comment]
It is because `crypto-js` lib version 4.0.0 used internally in this library is having a breaking changes that makes SimpleCrypto won't be able to run without native crypto module such as IE 10 or React Native. Please [read more here](https://github.com/brix/crypto-js#400).

We will probably publish two new releases, version 2.5.0 with `crypto-js` 3.3.0 to maintain compatibility and version 3.0.0 with `crypto-js` 4.0.0.

**Comment by danang-id** [comment]
> We will probably publish two new releases, version 2.5.0 with `crypto-js` rollbacked to 3.3.0 to maintain compatibility and version 3.0.0 with current `crypto-js` 4.0.0.

@enguerranws Expects the new release of version 2.5.0 within a day. For now, please stay at 2.2.0.

**Comment by enguerranws** [comment]
Wow, thank you really much for this quick answer. I'm looking forward for
this version.

**Comment by danang-id** [comment]
@enguerranws SimpleCrypto v2.5.0 is now available with compatibility support for IE 10 and React Native. Please do upgrade because v2.2.0 is vulnerable.
